name: ShopSphere CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shopsphere
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        env: 
           DATABASE_URL: mysql+pymysql://root:root@127.0.0.1:3306/shopsphere
        run: |
          pytest

      - name: Build Docker image
        working-directory: backend
        run: |
         docker build -t shopsphere-backend:latest .
      - name: Inspect OIDC claims
        uses: actions/github-script@v8
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            );
            console.log(`OIDC issuer: ${payload.iss}`);
            console.log(`OIDC audience: ${payload.aud}`);
            console.log(`OIDC subject: ${payload.sub}`);
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::957266312042:role/ShopSphereGitHubActionsRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        working-directory: backend
        run: |
          docker tag shopsphere-backend:latest 957266312042.dkr.ecr.us-east-1.amazonaws.com/shopsphere-backend:latest
          docker push 957266312042.dkr.ecr.us-east-1.amazonaws.com/shopsphere-backend:latest